/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExportLimit {
  'CSV_AND_PDF_COMBINED_MAX' : bigint,
  'MAX_OPERATIONS_PDF_AND_CSV' : bigint,
}
export interface LogEntry { 'message' : string, 'timestamp' : bigint }
export interface MiningProject {
  'id' : Uint8Array,
  'fcf' : [] | [number],
  'lom' : [] | [number],
  'npv' : [] | [number],
  'ocf' : [] | [number],
  'roi' : [] | [number],
  'ebitda' : [] | [number],
  'romTonnage' : number,
  'recoveryRate' : number,
  'commodityPrice' : number,
  'owner' : Principal,
  'capex' : number,
  'annualOpex' : [] | [number],
  'averageTaxRate' : number,
  'name' : string,
  'discountRate' : number,
  'depreciation' : number,
  'processingCost' : number,
  'annualProduction' : [] | [number],
  'lastModified' : bigint,
  'creationDate' : bigint,
  'miningCost' : number,
  'strippingRatio' : number,
  'paybackPeriod' : [] | [number],
  'gAndACost' : number,
  'oreGrade' : number,
  'oreReserves' : number,
  'annualRevenue' : [] | [number],
}
export interface SensitivityRange { 'max' : number, 'min' : number }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'premium' : ExportLimit } |
  { 'free' : ExportLimit } |
  { 'basic' : ExportLimit };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'lastResetTimestamp' : bigint,
  'exportsRemainingAnnual' : bigint,
  'name' : string,
  'tier' : SubscriptionTier,
  'modelsCreatedAnnual' : bigint,
  'email' : [] | [string],
  'romUsageCount' : bigint,
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canExport' : ActorMethod<[], boolean>,
  'clearPersistentLogs' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPremiumCheckoutSession' : ActorMethod<[string, string], string>,
  'decrementExportCount' : ActorMethod<[], undefined>,
  'deleteProject' : ActorMethod<[Uint8Array], undefined>,
  'fullResetExports' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPersistentLogs' : ActorMethod<[], Array<[bigint, LogEntry]>>,
  'getProject' : ActorMethod<[Uint8Array], MiningProject>,
  'getProjectsByOwner' : ActorMethod<[Principal], Array<MiningProject>>,
  'getRomUsageCount' : ActorMethod<[], bigint>,
  'getSensitivityRanges' : ActorMethod<[], Array<[string, SensitivityRange]>>,
  'getSortedProjects' : ActorMethod<[string], Array<MiningProject>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionTierInfo' : ActorMethod<[], Array<SubscriptionTier>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleStripeWebhook' : ActorMethod<[string, string], undefined>,
  'incrementRomUsage' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markUserAsPremium' : ActorMethod<[], undefined>,
  'refreshProjects' : ActorMethod<[], undefined>,
  'resetRomUsage' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProject' : ActorMethod<[MiningProject], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSensitivityRange' : ActorMethod<[string, SensitivityRange], undefined>,
  'updateSubscription' : ActorMethod<[Principal], undefined>,
  'upgradeSubscription' : ActorMethod<[string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];