/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExportLimit = IDL.Record({
  'CSV_AND_PDF_COMBINED_MAX' : IDL.Nat,
  'MAX_OPERATIONS_PDF_AND_CSV' : IDL.Nat,
});
export const SubscriptionTier = IDL.Variant({
  'premium' : ExportLimit,
  'free' : ExportLimit,
  'basic' : ExportLimit,
});
export const UserProfile = IDL.Record({
  'lastResetTimestamp' : IDL.Int,
  'exportsRemainingAnnual' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : SubscriptionTier,
  'modelsCreatedAnnual' : IDL.Nat,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'romUsageCount' : IDL.Nat,
  'organization' : IDL.Opt(IDL.Text),
});
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MiningProject = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'fcf' : IDL.Opt(IDL.Float64),
  'lom' : IDL.Opt(IDL.Float64),
  'npv' : IDL.Opt(IDL.Float64),
  'ocf' : IDL.Opt(IDL.Float64),
  'roi' : IDL.Opt(IDL.Float64),
  'ebitda' : IDL.Opt(IDL.Float64),
  'romTonnage' : IDL.Float64,
  'recoveryRate' : IDL.Float64,
  'commodityPrice' : IDL.Float64,
  'owner' : IDL.Principal,
  'capex' : IDL.Float64,
  'annualOpex' : IDL.Opt(IDL.Float64),
  'averageTaxRate' : IDL.Float64,
  'name' : IDL.Text,
  'discountRate' : IDL.Float64,
  'depreciation' : IDL.Float64,
  'processingCost' : IDL.Float64,
  'annualProduction' : IDL.Opt(IDL.Float64),
  'lastModified' : IDL.Int,
  'creationDate' : IDL.Int,
  'miningCost' : IDL.Float64,
  'strippingRatio' : IDL.Float64,
  'paybackPeriod' : IDL.Opt(IDL.Float64),
  'gAndACost' : IDL.Float64,
  'oreGrade' : IDL.Float64,
  'oreReserves' : IDL.Float64,
  'annualRevenue' : IDL.Opt(IDL.Float64),
});
export const SensitivityRange = IDL.Record({
  'max' : IDL.Float64,
  'min' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canExport' : IDL.Func([], [IDL.Bool], []),
  'clearPersistentLogs' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPremiumCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'decrementExportCount' : IDL.Func([], [], []),
  'deleteProject' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'fullResetExports' : IDL.Func([IDL.Principal], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersistentLogs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Int, LogEntry))],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Vec(IDL.Nat8)], [MiningProject], ['query']),
  'getProjectsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MiningProject)],
      ['query'],
    ),
  'getRomUsageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSensitivityRanges' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, SensitivityRange))],
      ['query'],
    ),
  'getSortedProjects' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MiningProject)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionTierInfo' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionTier)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleStripeWebhook' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'incrementRomUsage' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCurrentUserActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markUserAsPremium' : IDL.Func([], [], []),
  'refreshProjects' : IDL.Func([], [], []),
  'resetRomUsage' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProject' : IDL.Func([MiningProject], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSensitivityRange' : IDL.Func([IDL.Text, SensitivityRange], [], []),
  'updateSubscription' : IDL.Func([IDL.Principal], [], []),
  'upgradeSubscription' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExportLimit = IDL.Record({
    'CSV_AND_PDF_COMBINED_MAX' : IDL.Nat,
    'MAX_OPERATIONS_PDF_AND_CSV' : IDL.Nat,
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : ExportLimit,
    'free' : ExportLimit,
    'basic' : ExportLimit,
  });
  const UserProfile = IDL.Record({
    'lastResetTimestamp' : IDL.Int,
    'exportsRemainingAnnual' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : SubscriptionTier,
    'modelsCreatedAnnual' : IDL.Nat,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'romUsageCount' : IDL.Nat,
    'organization' : IDL.Opt(IDL.Text),
  });
  const LogEntry = IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Int });
  const MiningProject = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'fcf' : IDL.Opt(IDL.Float64),
    'lom' : IDL.Opt(IDL.Float64),
    'npv' : IDL.Opt(IDL.Float64),
    'ocf' : IDL.Opt(IDL.Float64),
    'roi' : IDL.Opt(IDL.Float64),
    'ebitda' : IDL.Opt(IDL.Float64),
    'romTonnage' : IDL.Float64,
    'recoveryRate' : IDL.Float64,
    'commodityPrice' : IDL.Float64,
    'owner' : IDL.Principal,
    'capex' : IDL.Float64,
    'annualOpex' : IDL.Opt(IDL.Float64),
    'averageTaxRate' : IDL.Float64,
    'name' : IDL.Text,
    'discountRate' : IDL.Float64,
    'depreciation' : IDL.Float64,
    'processingCost' : IDL.Float64,
    'annualProduction' : IDL.Opt(IDL.Float64),
    'lastModified' : IDL.Int,
    'creationDate' : IDL.Int,
    'miningCost' : IDL.Float64,
    'strippingRatio' : IDL.Float64,
    'paybackPeriod' : IDL.Opt(IDL.Float64),
    'gAndACost' : IDL.Float64,
    'oreGrade' : IDL.Float64,
    'oreReserves' : IDL.Float64,
    'annualRevenue' : IDL.Opt(IDL.Float64),
  });
  const SensitivityRange = IDL.Record({
    'max' : IDL.Float64,
    'min' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canExport' : IDL.Func([], [IDL.Bool], []),
    'clearPersistentLogs' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPremiumCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'decrementExportCount' : IDL.Func([], [], []),
    'deleteProject' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'fullResetExports' : IDL.Func([IDL.Principal], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersistentLogs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Int, LogEntry))],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Vec(IDL.Nat8)], [MiningProject], ['query']),
    'getProjectsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MiningProject)],
        ['query'],
      ),
    'getRomUsageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSensitivityRanges' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, SensitivityRange))],
        ['query'],
      ),
    'getSortedProjects' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MiningProject)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionTierInfo' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionTier)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleStripeWebhook' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'incrementRomUsage' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCurrentUserActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markUserAsPremium' : IDL.Func([], [], []),
    'refreshProjects' : IDL.Func([], [], []),
    'resetRomUsage' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProject' : IDL.Func([MiningProject], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserActiveStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSensitivityRange' : IDL.Func([IDL.Text, SensitivityRange], [], []),
    'updateSubscription' : IDL.Func([IDL.Principal], [], []),
    'upgradeSubscription' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };