/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MiningProject {
    id: Uint8Array;
    fcf?: number;
    lom?: number;
    npv?: number;
    ocf?: number;
    roi?: number;
    ebitda?: number;
    romTonnage: number;
    recoveryRate: number;
    commodityPrice: number;
    owner: Principal;
    capex: number;
    annualOpex?: number;
    averageTaxRate: number;
    name: string;
    discountRate: number;
    depreciation: number;
    processingCost: number;
    annualProduction?: number;
    lastModified: bigint;
    creationDate: bigint;
    miningCost: number;
    strippingRatio: number;
    paybackPeriod?: number;
    gAndACost: number;
    oreGrade: number;
    oreReserves: number;
    annualRevenue?: number;
}
export type ApiResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
};
export interface SensitivityRange {
    max: number;
    min: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type SubscriptionTier = {
    __kind__: "premium";
    premium: ExportLimit;
} | {
    __kind__: "free";
    free: ExportLimit;
} | {
    __kind__: "basic";
    basic: ExportLimit;
};
export interface ExportLimit {
    CSV_AND_PDF_COMBINED_MAX: bigint;
    MAX_OPERATIONS_PDF_AND_CSV: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface SaveProjectResult {
    status: ApiResult;
    projectId: Uint8Array;
    timestamp: bigint;
}
export interface LogEntry {
    message: string;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    lastResetTimestamp: bigint;
    exportsRemainingAnnual: bigint;
    name: string;
    tier: SubscriptionTier;
    modelsCreatedAnnual: bigint;
    email?: string;
    organization?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canExport(): Promise<boolean>;
    clearPersistentLogs(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    decrementExportCount(): Promise<void>;
    deleteProject(id: Uint8Array): Promise<void>;
    fullResetExports(principalId: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPersistentLogs(): Promise<Array<[bigint, LogEntry]>>;
    getProject(id: Uint8Array): Promise<MiningProject>;
    getProjectsByOwner(owner: Principal): Promise<Array<MiningProject>>;
    getSensitivityRanges(): Promise<Array<[string, SensitivityRange]>>;
    getSortedProjects(sortBy: string): Promise<Array<MiningProject>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionTierInfo(): Promise<Array<SubscriptionTier>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleStripeWebhook(sessionId: string, eventType: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    refreshProjects(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProject(project: MiningProject): Promise<SaveProjectResult>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSensitivityRange(setting: string, update: SensitivityRange): Promise<void>;
    updateSubscription(principalId: Principal): Promise<void>;
    upgradeSubscription(_tier: string, _planType: string | null): Promise<void>;
}
import type { ApiResult as _ApiResult, ExportLimit as _ExportLimit, MiningProject as _MiningProject, SaveProjectResult as _SaveProjectResult, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canExport(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canExport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canExport();
            return result;
        }
    }
    async clearPersistentLogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPersistentLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPersistentLogs();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async decrementExportCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementExportCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementExportCount();
            return result;
        }
    }
    async deleteProject(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async fullResetExports(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fullResetExports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fullResetExports(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersistentLogs(): Promise<Array<[bigint, LogEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentLogs();
            return result;
        }
    }
    async getProject(arg0: Uint8Array): Promise<MiningProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_MiningProject_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_MiningProject_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByOwner(arg0: Principal): Promise<Array<MiningProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByOwner(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByOwner(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensitivityRanges(): Promise<Array<[string, SensitivityRange]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensitivityRanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensitivityRanges();
            return result;
        }
    }
    async getSortedProjects(arg0: string): Promise<Array<MiningProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedProjects(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedProjects(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionTierInfo(): Promise<Array<SubscriptionTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionTierInfo();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionTierInfo();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleStripeWebhook(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleStripeWebhook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleStripeWebhook(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async refreshProjects(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshProjects();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProject(arg0: MiningProject): Promise<SaveProjectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProject(to_candid_MiningProject_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SaveProjectResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProject(to_candid_MiningProject_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SaveProjectResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSensitivityRange(arg0: string, arg1: SensitivityRange): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensitivityRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensitivityRange(arg0, arg1);
            return result;
        }
    }
    async updateSubscription(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(arg0);
            return result;
        }
    }
    async upgradeSubscription(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeSubscription(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeSubscription(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApiResult_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult): ApiResult {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MiningProject_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MiningProject): MiningProject {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SaveProjectResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaveProjectResult): SaveProjectResult {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Uint8Array;
    fcf: [] | [number];
    lom: [] | [number];
    npv: [] | [number];
    ocf: [] | [number];
    roi: [] | [number];
    ebitda: [] | [number];
    romTonnage: number;
    recoveryRate: number;
    commodityPrice: number;
    owner: Principal;
    capex: number;
    annualOpex: [] | [number];
    averageTaxRate: number;
    name: string;
    discountRate: number;
    depreciation: number;
    processingCost: number;
    annualProduction: [] | [number];
    lastModified: bigint;
    creationDate: bigint;
    miningCost: number;
    strippingRatio: number;
    paybackPeriod: [] | [number];
    gAndACost: number;
    oreGrade: number;
    oreReserves: number;
    annualRevenue: [] | [number];
}): {
    id: Uint8Array;
    fcf?: number;
    lom?: number;
    npv?: number;
    ocf?: number;
    roi?: number;
    ebitda?: number;
    romTonnage: number;
    recoveryRate: number;
    commodityPrice: number;
    owner: Principal;
    capex: number;
    annualOpex?: number;
    averageTaxRate: number;
    name: string;
    discountRate: number;
    depreciation: number;
    processingCost: number;
    annualProduction?: number;
    lastModified: bigint;
    creationDate: bigint;
    miningCost: number;
    strippingRatio: number;
    paybackPeriod?: number;
    gAndACost: number;
    oreGrade: number;
    oreReserves: number;
    annualRevenue?: number;
} {
    return {
        id: value.id,
        fcf: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.fcf)),
        lom: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lom)),
        npv: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.npv)),
        ocf: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.ocf)),
        roi: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.roi)),
        ebitda: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.ebitda)),
        romTonnage: value.romTonnage,
        recoveryRate: value.recoveryRate,
        commodityPrice: value.commodityPrice,
        owner: value.owner,
        capex: value.capex,
        annualOpex: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.annualOpex)),
        averageTaxRate: value.averageTaxRate,
        name: value.name,
        discountRate: value.discountRate,
        depreciation: value.depreciation,
        processingCost: value.processingCost,
        annualProduction: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.annualProduction)),
        lastModified: value.lastModified,
        creationDate: value.creationDate,
        miningCost: value.miningCost,
        strippingRatio: value.strippingRatio,
        paybackPeriod: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.paybackPeriod)),
        gAndACost: value.gAndACost,
        oreGrade: value.oreGrade,
        oreReserves: value.oreReserves,
        annualRevenue: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.annualRevenue))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApiResult;
    projectId: Uint8Array;
    timestamp: bigint;
}): {
    status: ApiResult;
    projectId: Uint8Array;
    timestamp: bigint;
} {
    return {
        status: from_candid_ApiResult_n27(_uploadFile, _downloadFile, value.status),
        projectId: value.projectId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastResetTimestamp: bigint;
    exportsRemainingAnnual: bigint;
    name: string;
    tier: _SubscriptionTier;
    modelsCreatedAnnual: bigint;
    email: [] | [string];
    organization: [] | [string];
}): {
    lastResetTimestamp: bigint;
    exportsRemainingAnnual: bigint;
    name: string;
    tier: SubscriptionTier;
    modelsCreatedAnnual: bigint;
    email?: string;
    organization?: string;
} {
    return {
        lastResetTimestamp: value.lastResetTimestamp,
        exportsRemainingAnnual: value.exportsRemainingAnnual,
        name: value.name,
        tier: from_candid_SubscriptionTier_n6(_uploadFile, _downloadFile, value.tier),
        modelsCreatedAnnual: value.modelsCreatedAnnual,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        organization: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.organization))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n17(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: null;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: null;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: _ExportLimit;
} | {
    free: _ExportLimit;
} | {
    basic: _ExportLimit;
}): {
    __kind__: "premium";
    premium: ExportLimit;
} | {
    __kind__: "free";
    free: ExportLimit;
} | {
    __kind__: "basic";
    basic: ExportLimit;
} {
    return "premium" in value ? {
        __kind__: "premium",
        premium: value.premium
    } : "free" in value ? {
        __kind__: "free",
        free: value.free
    } : "basic" in value ? {
        __kind__: "basic",
        basic: value.basic
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MiningProject>): Array<MiningProject> {
    return value.map((x)=>from_candid_MiningProject_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriptionTier>): Array<SubscriptionTier> {
    return value.map((x)=>from_candid_SubscriptionTier_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MiningProject_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MiningProject): _MiningProject {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastResetTimestamp: bigint;
    exportsRemainingAnnual: bigint;
    name: string;
    tier: SubscriptionTier;
    modelsCreatedAnnual: bigint;
    email?: string;
    organization?: string;
}): {
    lastResetTimestamp: bigint;
    exportsRemainingAnnual: bigint;
    name: string;
    tier: _SubscriptionTier;
    modelsCreatedAnnual: bigint;
    email: [] | [string];
    organization: [] | [string];
} {
    return {
        lastResetTimestamp: value.lastResetTimestamp,
        exportsRemainingAnnual: value.exportsRemainingAnnual,
        name: value.name,
        tier: to_candid_SubscriptionTier_n21(_uploadFile, _downloadFile, value.tier),
        modelsCreatedAnnual: value.modelsCreatedAnnual,
        email: value.email ? candid_some(value.email) : candid_none(),
        organization: value.organization ? candid_some(value.organization) : candid_none()
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Uint8Array;
    fcf?: number;
    lom?: number;
    npv?: number;
    ocf?: number;
    roi?: number;
    ebitda?: number;
    romTonnage: number;
    recoveryRate: number;
    commodityPrice: number;
    owner: Principal;
    capex: number;
    annualOpex?: number;
    averageTaxRate: number;
    name: string;
    discountRate: number;
    depreciation: number;
    processingCost: number;
    annualProduction?: number;
    lastModified: bigint;
    creationDate: bigint;
    miningCost: number;
    strippingRatio: number;
    paybackPeriod?: number;
    gAndACost: number;
    oreGrade: number;
    oreReserves: number;
    annualRevenue?: number;
}): {
    id: Uint8Array;
    fcf: [] | [number];
    lom: [] | [number];
    npv: [] | [number];
    ocf: [] | [number];
    roi: [] | [number];
    ebitda: [] | [number];
    romTonnage: number;
    recoveryRate: number;
    commodityPrice: number;
    owner: Principal;
    capex: number;
    annualOpex: [] | [number];
    averageTaxRate: number;
    name: string;
    discountRate: number;
    depreciation: number;
    processingCost: number;
    annualProduction: [] | [number];
    lastModified: bigint;
    creationDate: bigint;
    miningCost: number;
    strippingRatio: number;
    paybackPeriod: [] | [number];
    gAndACost: number;
    oreGrade: number;
    oreReserves: number;
    annualRevenue: [] | [number];
} {
    return {
        id: value.id,
        fcf: value.fcf ? candid_some(value.fcf) : candid_none(),
        lom: value.lom ? candid_some(value.lom) : candid_none(),
        npv: value.npv ? candid_some(value.npv) : candid_none(),
        ocf: value.ocf ? candid_some(value.ocf) : candid_none(),
        roi: value.roi ? candid_some(value.roi) : candid_none(),
        ebitda: value.ebitda ? candid_some(value.ebitda) : candid_none(),
        romTonnage: value.romTonnage,
        recoveryRate: value.recoveryRate,
        commodityPrice: value.commodityPrice,
        owner: value.owner,
        capex: value.capex,
        annualOpex: value.annualOpex ? candid_some(value.annualOpex) : candid_none(),
        averageTaxRate: value.averageTaxRate,
        name: value.name,
        discountRate: value.discountRate,
        depreciation: value.depreciation,
        processingCost: value.processingCost,
        annualProduction: value.annualProduction ? candid_some(value.annualProduction) : candid_none(),
        lastModified: value.lastModified,
        creationDate: value.creationDate,
        miningCost: value.miningCost,
        strippingRatio: value.strippingRatio,
        paybackPeriod: value.paybackPeriod ? candid_some(value.paybackPeriod) : candid_none(),
        gAndACost: value.gAndACost,
        oreGrade: value.oreGrade,
        oreReserves: value.oreReserves,
        annualRevenue: value.annualRevenue ? candid_some(value.annualRevenue) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "premium";
    premium: ExportLimit;
} | {
    __kind__: "free";
    free: ExportLimit;
} | {
    __kind__: "basic";
    basic: ExportLimit;
}): {
    premium: _ExportLimit;
} | {
    free: _ExportLimit;
} | {
    basic: _ExportLimit;
} {
    return value.__kind__ === "premium" ? {
        premium: value.premium
    } : value.__kind__ === "free" ? {
        free: value.free
    } : value.__kind__ === "basic" ? {
        basic: value.basic
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
